module.exports=function(grunt){
	grunt.initConfig({
		pkg:grunt.file.readJSON("package.json"),
		build_root:"build",
		js_root:"js",
		browserify:{
			compile:{
				expand:true,
				cwd:"src/js",
				src:["*.js"],
				dest:"build/js",
				ext:".js"
			}
		},
		uglify:{
			options:{
				sourceMap:true
			},
			compile:{
				expand:true,
				cwd:"build/js",
				src:["*.js",'!**/*min.js'],
				dest:"build/js",
				ext:".min.js"
			}
		},
		copy:{
			demo:{
				expand:true,
				cwd:'src/html',
				src:['*.html'],
				dest:'build/html',
				ext:'.html'
			}
		},
		less:{
			options:{
				compress:false
			},
			page:{
				expand:true,
				cwd:'src/css',
				src:['*.less'],
				dest:'build/css',
				ext:'.min.css'
			},
		},
		watch:{
			options:{
				livereload:true
			},
			js:{
				files:['src/js/*.js'],
				tasks:['browserify:compile']
			},
			html:{
				files:['src/html/*.html'],
				tasks:["copy:demo"]
			},
			css:{
				files:['src/css/*.less'],
				tasks:['less:page']
			}
		}
	});
	grunt.loadNpmTasks("grunt-contrib-watch");
	grunt.loadNpmTasks("grunt-contrib-uglify");
	grunt.loadNpmTasks("grunt-contrib-copy");
	grunt.loadNpmTasks("grunt-browserify");
	grunt.loadNpmTasks("grunt-contrib-less");

	grunt.registerTask("default",['browserify','uglify','less',"copy"]);
};